---
title: 'Normalize Counts and Batch Effect Investigations '
author: "Jenny Smith"
date: "February 4, 2018"
output: html_document
---


#Set-up 

```{r setup}
library(knitr)
knitr::opts_chunk$set(tidy.opts=list(width.cutoff=50),tidy=TRUE, fig.align='center', fig.height=5, fig.width=8, dpi = 600)
knitr::opts_knit$set(root.dir = '~/Documents/GitHub/RNAseq_Cancer_Biomarkers/')
options(stringsAsFactors = FALSE)
```


```{r message = FALSE, warning=FALSE}
library(stringr)
library(magrittr)
library(ggplot2)
library(dplyr)
library(tibble)
library(tidyr)
getwd()
```


#Read in Counts 

```{r}
counts <- read.csv("TARGET_NBL_AML_RT_WT_HTSeq_Counts.csv",row.names = 1)

head(counts[,1:5])
dim(counts)
```



#TMM Normalization 

```{r}
library(limma)
library(edgeR)
```

```{r}
dge <- DGEList(counts = counts)
```

```{r}
samp <- ncol(counts)

keep.dge <- rowSums(cpm(dge) >= 1) >= max(2,(0.05*samp)) #5% of AML samples has cpm of at least 1 for a gene
dge <- dge[keep.dge,] #subset for those genes with cmp >= 1 per gene in AML samples
dge <- calcNormFactors(dge) #Do TMM normalization
```

```{r}
dim(dge) #21,407 genes meet these criteria by 474 

cpm <- cpm(dge,log = TRUE, prior.count = 1)

head(cpm[,1:5])
# write.csv(cpm, "TARGET_NBL_AML_WT_RT_TMMCPM_log2_Norm_Counts.csv", row.names = TRUE)
```
 


#Use the Merged Clinical and TMMCPM 

This was created by David Lee Using Python()
See D-V-DLee for Github 


```{r}
AML.CDE <- read.csv("scripts/AML_assay_clinical.csv", row.names = 1) %>%
  set_rownames(.$TARGET.USI)

dim(AML.CDE)
head(AML.CDE[,1:5])
```


```{r}
table(AML.CDE$Diagnostic.ID)
```

```{r}
NBL.CDE <- read.csv("scripts/NBL_assay_clinical.csv", row.names = 1)

dim(NBL.CDE)
head(NBL.CDE[,1:5])
```

```{r}
table(NBL.CDE$Diagnostic.ID)
```


```{r}
WT.CDE <- read.csv("scripts/WT_assay_clinical.csv", row.names = 1)

dim(WT.CDE)
head(WT.CDE[,1:5])
```


```{r}
table(WT.CDE$Diagnostic.ID)
```

Remove Non-diagnostic samples: 04A, 40A, 02A, 06A, 11A


#Examine boxplots of the 

```{r}
cpm.m <- cpm %>% 
  rownames_to_column("Gene") %>% 
  gather(USI,Log2.CPM, -Gene) %>%
  mutate(Group=case_when(
    grepl("TARGET.30.", USI) ~ "NBL",
    grepl("TARGET.20.", USI) ~ "AML",
    grepl("TARGET.50.", USI) ~ "WT"))

head(cpm.m)
```

```{r}
table(cpm.m$Group)
```


```{r fig.width=18, fig.height=6}
ggplot(cpm.m[cpm.m$Group != "WT",], 
       aes(x = reorder(USI, Log2.CPM, FUN = median), y = Log2.CPM, fill=Group)) +
  geom_boxplot()
```



```{r}
sessionInfo()
```




